#! /bin/sh

### BEGIN INIT INFO
# Provides:          acpi-reboot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting acpi-reboot"
    /opt/rpi-utils/acpi-reboot &
    ;;
  stop)
    echo "Stopping acpi-reboot"
    pkill -f /opt/rpi-utils/acpi-reboot
    ;;
  *)
    echo "Usage: /etc/init.d/acpi-reboot-service {start|stop}"
    exit 1
    ;;
esac

exit 0
