#! /bin/sh

### BEGIN INIT INFO
# Provides:          cpu-temp-monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting cpu-temp-monitor"
    /opt/rpi-utils/cputemp &
    ;;
  stop)
    echo "Stopping cpu-temp-monitor"
    pkill -f /opt/rpi-utils/cputemp
    ;;
  *)
    echo "Usage: /etc/init.d/cpu-temp-monitor {start|stop}"
    exit 1
    ;;
esac

exit 0
