#! /bin/sh

### BEGIN INIT INFO
# Provides:          link-status-led
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting link-status-led"
    /opt/rpi-utils/ip-connections &
    ;;
  stop)
    echo "Stopping link-status-led"
    pkill -f /opt/rpi-utils/ip-connections
    ;;
  *)
    echo "Usage: /etc/init.d/link-status-service {start|stop}"
    exit 1
    ;;
esac

exit 0
