#!/usr/bin/python

import RPi.GPIO as GPIO
import subprocess

if __name__ == '__main__':
  GPIO.setmode(GPIO.BCM)
  GPIO.setwarnings(False)
  GPIO.setup(2, GPIO.IN, pull_up_down=GPIO.PUD_UP)
  GPIO.wait_for_edge(2, GPIO.FALLING)
  subprocess.call(['sudo','reboot'], shell=False)
