#!/usr/bin/python

import RPi.GPIO as GPIO
import subprocess

if __name__ == '__main__':
  GPIO.setmode(GPIO.BCM)
  GPIO.setwarnings(False)
  GPIO.setup(3, GPIO.IN, pull_up_down=GPIO.PUD_UP)
  GPIO.wait_for_edge(3, GPIO.FALLING)
  subprocess.call(['sudo','shutdown', '-h', 'now'], shell=False)
