#!/usr/bin/python
import sys
import RPi.GPIO as GPIO
import time

if __name__ == '__main__':
  LED = int(sys.argv[1])
  GPIO.setmode(GPIO.BCM)
  GPIO.setwarnings(False)
  GPIO.setup(LED, GPIO.OUT)
  while True:
    #print "on"
    GPIO.output(LED, GPIO.HIGH)
    time.sleep(1)
    #print "off"
    GPIO.output(LED, GPIO.LOW)
    time.sleep(1)
