#!/usr/bin/python
import sys
import RPi.GPIO as GPIO

if __name__ == '__main__':
  LED = int(sys.argv[1])
  GPIO.setmode(GPIO.BCM)
  GPIO.setwarnings(False)
  GPIO.setup(LED, GPIO.OUT)
  GPIO.output(LED, GPIO.HIGH)
