#!/usr/bin/python
import sys
import RPi.GPIO as GPIO
import time

if __name__ == '__main__':
  LED = 11
  GPIO.setmode(GPIO.BCM)
  GPIO.setwarnings(False)
  GPIO.setup(LED, GPIO.OUT)
  GPIO.output(LED, GPIO.HIGH)
  time.sleep(2)
  GPIO.output(LED, GPIO.LOW)
