#!/usr/bin/python
import subprocess
import json
import RPi.GPIO as GPIO
import time;

LED = 27
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(LED, GPIO.OUT)

def api_check():
  result = subprocess.Popen(['curl', '-sS', '-m', '15', '--socks5-hostname', '127.0.0.1:9050', 'https://check.torproject.org/api/ip'], stdout=subprocess.PIPE).communicate()[0]
  #print result
  return json.loads(result)

def format(data):
  result = '';
  if data['IsTor']:
    result = result + 'OK\t';
  else:
    result = result + 'INSECURE\t';
  result = result + data['IP']
  return result

if __name__ == '__main__':
  while True:
    try:
      data = api_check();
      #print str(data);
      if data['IsTor']:
        #print str(data['IsTor']) + ' ' + data['IP']
        GPIO.output(LED, GPIO.HIGH)
      else:
        GPIO.output(LED, GPIO.LOW)
    except:
      GPIO.output(LED, GPIO.LOW)
    time.sleep(5)
